import Foundation

// MARK: - CaptionTrack

/// A single caption track as returned by YouTube's /player InnerTube endpoint.
/// `baseURL` serves the timed-text document used for the transcript.
public struct CaptionTrack: Identifiable, Hashable, Sendable {
    public let id: String               // vssId, e.g. ".en" or "a.en"
    public let baseURL: URL
    public let name: String             // Localised display name, e.g. "English"
    public let languageCode: String     // ISO 639-1, e.g. "en"
    public let isAutoGenerated: Bool    // true when vssId starts with "a." or kind == "asr"
}
