import Foundation

// MARK: - CaptionTrack

/// A single caption track as returned by YouTube's /player InnerTube endpoint.
/// Each track provides a WebVTT file at `baseURL` containing time-coded text cues.
public struct CaptionTrack: Identifiable, Hashable, Sendable {
    public let id: String               // vssId, e.g. ".en" or "a.en"
    public let baseURL: URL
    public let name: String             // Localised display name, e.g. "English"
    public let languageCode: String     // ISO 639-1, e.g. "en"
    public let isAutoGenerated: Bool    // true when vssId starts with "a." or kind == "asr"
}

// MARK: - CaptionCue

public struct CaptionCue: Sendable {
    public let startTime: TimeInterval
    public let endTime: TimeInterval
    public let text: String
}

// MARK: - WebVTTParser

public actor WebVTTParser {
    private let session: URLSession

    public init(session: URLSession = .shared) {
        self.session = session
    }

    public func fetchCues(from url: URL) async throws -> [CaptionCue] {
        var request = URLRequest(url: url)
        request.setValue("text/vtt, */*", forHTTPHeaderField: "Accept")
        let (data, _) = try await session.data(for: request)
        guard let text = String(data: data, encoding: .utf8) else {
            throw URLError(.cannotDecodeContentData)
        }
        return parseVTT(text)
    }

    nonisolated public func parseVTT(_ text: String) -> [CaptionCue] {
        var cues: [CaptionCue] = []
        let lines = text.components(separatedBy: .newlines)
        var i = 0

        while i < lines.count, !lines[i].contains("-->") { i += 1 }

        while i < lines.count {
            let line = lines[i].trimmingCharacters(in: .whitespaces)

            if line.isEmpty { i += 1; continue }
            if !line.contains("-->") { i += 1; continue }

            let arrowParts = line.components(separatedBy: " --> ")
            guard arrowParts.count >= 2,
                  let start = parseVTTTimestamp(arrowParts[0].trimmingCharacters(in: .whitespaces)),
                  let end = parseVTTTimestamp(
                    arrowParts[1].components(separatedBy: " ").first ?? ""
                  )
            else { i += 1; continue }

            i += 1

            var textLines: [String] = []
            while i < lines.count {
                let tl = lines[i].trimmingCharacters(in: .whitespaces)
                if tl.isEmpty { break }
                textLines.append(tl)
                i += 1
            }

            let raw = textLines.joined(separator: "\n")
            let cleaned = stripVTTTags(raw).decodingHTMLEntities()
                .trimmingCharacters(in: .whitespacesAndNewlines)
            if !cleaned.isEmpty {
                cues.append(CaptionCue(startTime: start, endTime: end, text: cleaned))
            }
        }

        return cues.sorted { $0.startTime < $1.startTime }
    }

    nonisolated private func parseVTTTimestamp(_ s: String) -> TimeInterval? {
        let parts = s.components(separatedBy: ":")
        switch parts.count {
        case 2:
            guard let m = Double(parts[0]), let sec = Double(parts[1]) else { return nil }
            return m * 60 + sec
        case 3:
            guard let h = Double(parts[0]), let m = Double(parts[1]), let sec = Double(parts[2]) else { return nil }
            return h * 3600 + m * 60 + sec
        default:
            return nil
        }
    }

    nonisolated private func stripVTTTags(_ s: String) -> String {
        var result = ""
        result.reserveCapacity(s.count)
        var inTag = false
        for ch in s {
            if ch == "<" { inTag = true } else if ch == ">" { inTag = false } else if !inTag { result.append(ch) }
        }
        return result
    }
}

private extension String {
    func decodingHTMLEntities() -> String {
        self
            .replacingOccurrences(of: "&amp;", with: "&")
            .replacingOccurrences(of: "&lt;", with: "<")
            .replacingOccurrences(of: "&gt;", with: ">")
            .replacingOccurrences(of: "&quot;", with: "\"")
            .replacingOccurrences(of: "&#39;", with: "'")
            .replacingOccurrences(of: "&nbsp;", with: " ")
            .replacingOccurrences(of: "&#x27;", with: "'")
            .replacingOccurrences(of: "&#x2F;", with: "/")
    }
}
