#if !os(macOS)
import AVKit
import MediaPlayer
import OSLog
import UnwatchedShared

extension AVPlayerViewModel {

    // MARK: - Transcript

    @MainActor
    func applyTranscriptUrl(from info: PlayerInfo) {
        let tracks = info.captionTracks
        player.availableCaptionTracks = tracks
        guard !tracks.isEmpty else {
            player.transcriptUrl = ""
            return
        }
        let locale = Locale.current.language.languageCode?.identifier ?? "en"
        let matching = tracks.filter { $0.languageCode == locale }
        let selected: CaptionTrack
        if matching.isEmpty {
            selected = tracks[0]
        } else if matching.count == 1 {
            selected = matching[0]
        } else {
            selected = matching.first { !$0.isAutoGenerated } ?? matching[0]
        }
        // CaptionTrack.baseURL has ?fmt=vtt for WebVTTParser, but TranscriptParser
        // uses XMLParser and expects the default timedText XML format — strip fmt.
        var comps = URLComponents(url: selected.baseURL, resolvingAgainstBaseURL: false)
        let items = comps?.queryItems?.filter { $0.name != "fmt" }
        comps?.queryItems = items
        player.transcriptUrl = (comps?.url ?? selected.baseURL).absoluteString
    }

    // MARK: - Remote Commands

    func setupRemoteCommandsIfNeeded() {
        guard !commandsSetUp else { return }
        commandsSetUp = true

        let theAVPlayer = avPlayer
        let thePlayer = player
        let center = MPRemoteCommandCenter.shared()

        center.playCommand.isEnabled = true
        center.playCommand.addTarget { _ in
            Task { @MainActor in thePlayer.isPlaying = true }
            return .success
        }

        center.pauseCommand.isEnabled = true
        center.pauseCommand.addTarget { _ in
            Task { @MainActor in thePlayer.isPlaying = false }
            return .success
        }

        center.togglePlayPauseCommand.isEnabled = true
        center.togglePlayPauseCommand.addTarget { _ in
            Task { @MainActor in thePlayer.isPlaying.toggle() }
            return .success
        }

        center.skipForwardCommand.isEnabled = true
        center.skipForwardCommand.preferredIntervals = [15]
        center.skipForwardCommand.addTarget { event in
            let interval = (event as? MPSkipIntervalCommandEvent)?.interval ?? 15
            let target = theAVPlayer.currentTime().seconds + interval
            theAVPlayer.seek(to: CMTime(seconds: target, preferredTimescale: 600),
                             toleranceBefore: .zero, toleranceAfter: .zero)
            Self.patchElapsedTime(target)
            return .success
        }

        center.skipBackwardCommand.isEnabled = true
        center.skipBackwardCommand.preferredIntervals = [15]
        center.skipBackwardCommand.addTarget { event in
            let interval = (event as? MPSkipIntervalCommandEvent)?.interval ?? 15
            let target = max(0, theAVPlayer.currentTime().seconds - interval)
            theAVPlayer.seek(to: CMTime(seconds: target, preferredTimescale: 600),
                             toleranceBefore: .zero, toleranceAfter: .zero)
            Self.patchElapsedTime(target)
            return .success
        }

        // Headphone inline remotes and AirPods send next/previous track, not skip.
        center.nextTrackCommand.isEnabled = true
        center.nextTrackCommand.addTarget { _ in
            let target = theAVPlayer.currentTime().seconds + 15
            theAVPlayer.seek(to: CMTime(seconds: target, preferredTimescale: 600),
                             toleranceBefore: .zero, toleranceAfter: .zero)
            Self.patchElapsedTime(target)
            return .success
        }

        center.previousTrackCommand.isEnabled = true
        center.previousTrackCommand.addTarget { _ in
            let target = max(0, theAVPlayer.currentTime().seconds - 15)
            theAVPlayer.seek(to: CMTime(seconds: target, preferredTimescale: 600),
                             toleranceBefore: .zero, toleranceAfter: .zero)
            Self.patchElapsedTime(target)
            return .success
        }

        center.changePlaybackPositionCommand.isEnabled = true
        center.changePlaybackPositionCommand.addTarget { event in
            guard let e = event as? MPChangePlaybackPositionCommandEvent else { return .commandFailed }
            theAVPlayer.seek(to: CMTime(seconds: e.positionTime, preferredTimescale: 600),
                             toleranceBefore: .zero, toleranceAfter: .zero)
            Self.patchElapsedTime(e.positionTime)
            return .success
        }
    }

    func teardownRemoteCommands() {
        let center = MPRemoteCommandCenter.shared()
        center.playCommand.removeTarget(nil)
        center.pauseCommand.removeTarget(nil)
        center.togglePlayPauseCommand.removeTarget(nil)
        center.skipForwardCommand.removeTarget(nil)
        center.skipBackwardCommand.removeTarget(nil)
        center.nextTrackCommand.removeTarget(nil)
        center.previousTrackCommand.removeTarget(nil)
        center.changePlaybackPositionCommand.removeTarget(nil)
        commandsSetUp = false
        MPNowPlayingInfoCenter.default().nowPlayingInfo = nil
    }

    // MARK: - Now Playing Info

    @MainActor
    func updateNowPlayingInfo(elapsed elapsedOverride: Double? = nil) {
        guard let video = player.video else {
            MPNowPlayingInfoCenter.default().nowPlayingInfo = nil
            return
        }

        let raw = elapsedOverride ?? avPlayer.currentTime().seconds
        let elapsed = (raw.isNaN || raw.isInfinite) ? 0.0 : raw
        var info: [String: Any] = [
            MPMediaItemPropertyTitle: video.title,
            MPNowPlayingInfoPropertyPlaybackRate: player.isPlaying ? player.playbackSpeed : 0.0,
            MPNowPlayingInfoPropertyElapsedPlaybackTime: elapsed,
            MPNowPlayingInfoPropertyMediaType: MPNowPlayingInfoMediaType.video.rawValue
        ]

        if let duration = video.duration, duration > 0 {
            info[MPMediaItemPropertyPlaybackDuration] = duration
        }
        if let author = video.subscription?.author {
            info[MPMediaItemPropertyArtist] = author
        }
        if let artwork = artworkImage {
            info[MPMediaItemPropertyArtwork] = MPMediaItemArtwork(boundsSize: artwork.size) { _ in artwork }
        }

        MPNowPlayingInfoCenter.default().nowPlayingInfo = info
    }

    func fetchArtwork(for video: Video) {
        let videoId = video.youtubeId
        // Prefer maxresdefault (1280×720, 16:9) to avoid the black letterbox bars
        // that appear in hqdefault (480×360, 4:3).
        let candidates: [URL] = [
            UrlService.getImageUrl(video.thumbnailUrl, .max),
            video.thumbnailUrl
        ].compactMap { $0 }
        Task {
            for url in candidates {
                guard let (data, response) = try? await URLSession.shared.data(from: url),
                      (response as? HTTPURLResponse)?.statusCode == 200,
                      let image = UIImage(data: data) else { continue }
                await MainActor.run {
                    guard player.video?.youtubeId == videoId else { return }
                    artworkImage = image
                    updateNowPlayingInfo()
                }
                return
            }
        }
    }

    // Updates only the elapsed time in the existing now playing info dict.
    // Used from remote command handlers (non-isolated) to avoid a full rebuild.
    static func patchElapsedTime(_ elapsed: Double) {
        var info = MPNowPlayingInfoCenter.default().nowPlayingInfo ?? [:]
        info[MPNowPlayingInfoPropertyElapsedPlaybackTime] = elapsed
        MPNowPlayingInfoCenter.default().nowPlayingInfo = info
    }
}
#endif
