import AVKit
import MediaPlayer
import OSLog
import UnwatchedShared

extension AVPlayerViewModel {

    // MARK: - Transcript

    /// iOS/Android/AndroidVR often omit captions from their `/player` response even when present.
    private static let captionReliableClients: Set<String> = ["MWEB", "TVEmbedded", "WebSafari"]

    @MainActor
    func applyTranscriptUrl(from info: PlayerInfo, client: String) {
        if let url = Self.selectTranscriptUrl(from: info.captionTracks) {
            player.transcriptUrl = url
            return
        }
        guard Self.captionReliableClients.contains(client) else {
            confirmNoTranscript(videoId: info.video.id)
            return
        }
        player.transcriptUrl = ""
    }

    private static func selectTranscriptUrl(from tracks: [CaptionTrack]) -> String? {
        guard !tracks.isEmpty else { return nil }
        let locale = Locale.current.language.languageCode?.identifier ?? "en"
        let matching = tracks.filter { $0.languageCode == locale }
        let selected: CaptionTrack
        if matching.isEmpty {
            selected = tracks[0]
        } else if matching.count == 1 {
            selected = matching[0]
        } else {
            selected = matching.first { !$0.isAutoGenerated } ?? matching[0]
        }
        return selected.baseURL.absoluteString
    }

    /// Re-checks with a reliable client once per video before trusting "no captions".
    @MainActor
    private func confirmNoTranscript(videoId: String) {
        guard transcriptConfirmationVideoId != videoId else { return }
        transcriptConfirmationVideoId = videoId
        Task {
            guard let info = try? await self.api.fetchPlayerInfoMWEB(videoId: videoId) else { return }
            guard !Task.isCancelled, player.video?.youtubeId == videoId else { return }
            player.transcriptUrl = Self.selectTranscriptUrl(from: info.captionTracks) ?? ""
        }
    }

    // MARK: - Remote Commands

    func setupRemoteCommandsIfNeeded() {
        guard !commandsSetUp else { return }
        commandsSetUp = true

        let thePlayer = player
        let center = MPRemoteCommandCenter.shared()

        center.playCommand.isEnabled = true
        center.playCommand.addTarget { _ in
            Task { @MainActor in thePlayer.play() }
            return .success
        }

        center.pauseCommand.isEnabled = true
        center.pauseCommand.addTarget { _ in
            Task { @MainActor in thePlayer.pause() }
            return .success
        }

        center.togglePlayPauseCommand.isEnabled = true
        center.togglePlayPauseCommand.addTarget { _ in
            Task { @MainActor in thePlayer.isPlaying ? thePlayer.pause() : thePlayer.play() }
            return .success
        }

        center.skipForwardCommand.isEnabled = true
        center.skipForwardCommand.preferredIntervals = [NSNumber(value: thePlayer.userSeekSeconds)]
        center.skipForwardCommand.addTarget { event in
            let interval = (event as? MPSkipIntervalCommandEvent)?.interval ?? thePlayer.userSeekSeconds
            Task { @MainActor in Self.skip(by: interval) }
            return .success
        }

        center.skipBackwardCommand.isEnabled = true
        center.skipBackwardCommand.preferredIntervals = [NSNumber(value: thePlayer.userSeekSeconds)]
        center.skipBackwardCommand.addTarget { event in
            let interval = (event as? MPSkipIntervalCommandEvent)?.interval ?? thePlayer.userSeekSeconds
            Task { @MainActor in Self.skip(by: -interval) }
            return .success
        }

        // Headphone inline remotes and AirPods send next/previous track, not skip.
        center.nextTrackCommand.isEnabled = true
        center.nextTrackCommand.addTarget { _ in
            Task { @MainActor in Self.skip(by: thePlayer.userSeekSeconds) }
            return .success
        }

        center.previousTrackCommand.isEnabled = true
        center.previousTrackCommand.addTarget { _ in
            Task { @MainActor in Self.skip(by: -thePlayer.userSeekSeconds) }
            return .success
        }

        center.changePlaybackPositionCommand.isEnabled = true
        center.changePlaybackPositionCommand.addTarget { event in
            guard let e = event as? MPChangePlaybackPositionCommandEvent else { return .commandFailed }
            Task { @MainActor in Self.seek(toEpisodeTime: e.positionTime) }
            return .success
        }
    }

    /// The lock screen is given the episode's own timeline — that's the elapsed time and duration it's sent — so its
    /// commands are answered in it too, and a skip covers the same ground there as it does in the app.
    @MainActor
    private static func skip(by interval: Double) {
        seek(toEpisodeTime: max(0, AVPlayerViewModel.shared.currentFileTime() + interval))
    }

    @MainActor
    private static func seek(toEpisodeTime time: Double) {
        let vm = AVPlayerViewModel.shared
        vm.avPlayer.seek(to: CMTime(seconds: vm.playerTime(time), preferredTimescale: 600),
                         toleranceBefore: .zero, toleranceAfter: .zero)
        patchElapsedTime(time)
    }

    func teardownRemoteCommands() {
        let center = MPRemoteCommandCenter.shared()
        center.playCommand.removeTarget(nil)
        center.pauseCommand.removeTarget(nil)
        center.togglePlayPauseCommand.removeTarget(nil)
        center.skipForwardCommand.removeTarget(nil)
        center.skipBackwardCommand.removeTarget(nil)
        center.nextTrackCommand.removeTarget(nil)
        center.previousTrackCommand.removeTarget(nil)
        center.changePlaybackPositionCommand.removeTarget(nil)
        commandsSetUp = false
        MPNowPlayingInfoCenter.default().nowPlayingInfo = nil
    }

    // MARK: - Now Playing Info

    @MainActor
    func updateNowPlayingInfo(elapsed elapsedOverride: Double? = nil) {
        guard let video = player.video else {
            MPNowPlayingInfoCenter.default().nowPlayingInfo = nil
            return
        }

        let raw = elapsedOverride ?? lastObservedTime ?? currentFileTime()
        let elapsed = (raw.isNaN || raw.isInfinite) ? 0.0 : raw
        var info: [String: Any] = [
            MPMediaItemPropertyTitle: video.title,
            MPNowPlayingInfoPropertyPlaybackRate: player.isPlaying ? player.playbackSpeed : 0.0,
            MPNowPlayingInfoPropertyElapsedPlaybackTime: elapsed,
            MPNowPlayingInfoPropertyMediaType: MPNowPlayingInfoMediaType.video.rawValue
        ]

        if let duration = video.duration, duration > 0 {
            info[MPMediaItemPropertyPlaybackDuration] = duration
        }
        if let author = video.subscription?.author {
            info[MPMediaItemPropertyArtist] = author
        }
        if let artwork = artworkImage {
            info[MPMediaItemPropertyArtwork] = MPMediaItemArtwork(boundsSize: artwork.size) { _ in artwork }
        }

        MPNowPlayingInfoCenter.default().nowPlayingInfo = info
    }

    @MainActor
    func handleChapterChanged() {
        fetchArtwork()
    }

    /// The lock screen shows what the player shows, chapter artwork included, so this re-runs whenever
    /// `PlayerManager.displayArtworkUrl` changes rather than once per video.
    @MainActor
    func fetchArtwork() {
        let urls = player.displayArtworkUrls.compactMap { $0 }
        guard urls != fetchedArtworkUrls else { return }
        fetchedArtworkUrls = urls
        guard !urls.isEmpty else {
            artworkImage = nil
            updateNowPlayingInfo()
            return
        }
        // Prefer maxresdefault (1280×720, 16:9) to avoid the black letterbox bars that appear in hqdefault (480×360,
        // 4:3).
        var seen = Set<URL>()
        let candidates = urls
            .flatMap { [UrlService.getImageUrl($0, .max), $0] }
            .compactMap { $0 }
            .filter { seen.insert($0).inserted }
        Task {
            for url in candidates {
                guard let data = await ImageService.imageData(for: url),
                      let image = PlatformImage(data: data) else { continue }
                await MainActor.run {
                    guard player.displayArtworkUrls.compactMap({ $0 }) == urls else { return }
                    artworkImage = image
                    updateNowPlayingInfo()
                }
                return
            }
        }
    }

    // Updates only the elapsed time in the existing now playing info dict.
    // Used from remote command handlers (non-isolated) to avoid a full rebuild.
    static func patchElapsedTime(_ elapsed: Double) {
        var info = MPNowPlayingInfoCenter.default().nowPlayingInfo ?? [:]
        info[MPNowPlayingInfoPropertyElapsedPlaybackTime] = elapsed
        MPNowPlayingInfoCenter.default().nowPlayingInfo = info
    }
}
